name: aoc-utils
version: 1.2.0
github: "Riddarvid/aoc-utils"
license: BSD3
author: "Riddarvid"
maintainer: "code@arvid-rydberg.se"
copyright: "2023 Riddarvid"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/aoc-utils#readme>

dependencies:
  - base >= 4.7 && < 5
  - hashable
  - containers
  - parsec
  - unordered-containers
  - mtl
  - optparse-applicative
  - time
  - regex-pcre
  - filepath

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
