name: aoc-utils
version: 0.1.0.0
github: "Riddarvid/aoc-utils"
license: BSD3
author: "Riddarvid"
maintainer: "code@arvid-rydberg.se"
copyright: "2023 Riddarvid"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/aoc-utils#readme>

dependencies:
  - base >= 4.7 && < 5
  - hashable >= 1.4.2.0
  - containers >= 0.6.7
  - gloss >= 1.13.2.2
  - parsec >= 3.1.16.1
  - unordered-containers >= 0.2.19.1
  - mtl >= 2.2.2
  - optparse-applicative >= 0.17.0.0
  - time >= 1.12.2
  - regex-pcre >= 0.95.0.0
  - filepath >= 1.4.2.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
